version: '2'

services:
    db:
        image: mysql
        command: mysqld --user=root --verbose --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: ./${SYMFONY_APP_NAME}/php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - ../${SYMFONY_APP_NAME}-back:/var/www/${SYMFONY_APP_NAME}
            - ../logs/${SYMFONY_APP_NAME}:/var/www/${SYMFONY_APP_NAME}/var/logs
            - .//${SYMFONY_APP_NAME}/php7-fpm/php-timezone.ini:/usr/local/etc/php/conf.d/docker-php-timezone.ini
    nginx:
        build: ./nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ../logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
